# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 332)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(632, 332))
        MainWindow.setMaximumSize(QtCore.QSize(632, 332))
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.filesButton = QtWidgets.QPushButton(self.centralwidget)
        self.filesButton.setGeometry(QtCore.QRect(40, 240, 260, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.filesButton.setFont(font)
        self.filesButton.setObjectName("filesButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setGeometry(QtCore.QRect(0, 200, 640, 5))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(320, 50, 3, 150))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 291, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.checkValue = QtWidgets.QCheckBox(self.centralwidget)
        self.checkValue.setGeometry(QtCore.QRect(40, 75, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkValue.setFont(font)
        self.checkValue.setIconSize(QtCore.QSize(32, 32))
        self.checkValue.setObjectName("checkValue")
        self.checkLogs = QtWidgets.QCheckBox(self.centralwidget)
        self.checkLogs.setGeometry(QtCore.QRect(40, 125, 271, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkLogs.setFont(font)
        self.checkLogs.setObjectName("checkLogs")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 50, 291, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkRemove = QtWidgets.QCheckBox(self.centralwidget)
        self.checkRemove.setGeometry(QtCore.QRect(340, 75, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkRemove.setFont(font)
        self.checkRemove.setIconSize(QtCore.QSize(32, 32))
        self.checkRemove.setChecked(True)
        self.checkRemove.setTristate(False)
        self.checkRemove.setObjectName("checkRemove")
        self.checkXML = QtWidgets.QCheckBox(self.centralwidget)
        self.checkXML.setGeometry(QtCore.QRect(340, 100, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkXML.setFont(font)
        self.checkXML.setIconSize(QtCore.QSize(32, 32))
        self.checkXML.setChecked(True)
        self.checkXML.setTristate(False)
        self.checkXML.setObjectName("checkXML")
        self.checkZIP = QtWidgets.QCheckBox(self.centralwidget)
        self.checkZIP.setGeometry(QtCore.QRect(340, 125, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkZIP.setFont(font)
        self.checkZIP.setIconSize(QtCore.QSize(32, 32))
        self.checkZIP.setChecked(True)
        self.checkZIP.setTristate(False)
        self.checkZIP.setObjectName("checkZIP")
        self.clearLogs = QtWidgets.QCheckBox(self.centralwidget)
        self.clearLogs.setGeometry(QtCore.QRect(40, 150, 271, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearLogs.setFont(font)
        self.clearLogs.setObjectName("clearLogs")
        self.asArray = QtWidgets.QCheckBox(self.centralwidget)
        self.asArray.setGeometry(QtCore.QRect(40, 100, 271, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.asArray.setFont(font)
        self.asArray.setObjectName("asArray")
        self.saveOptions = QtWidgets.QPushButton(self.centralwidget)
        self.saveOptions.setGeometry(QtCore.QRect(535, 5, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveOptions.setFont(font)
        self.saveOptions.setObjectName("saveOptions")
        self.dirButton = QtWidgets.QPushButton(self.centralwidget)
        self.dirButton.setGeometry(QtCore.QRect(340, 240, 260, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.dirButton.setFont(font)
        self.dirButton.setObjectName("dirButton")
        self.messageText = QtWidgets.QLabel(self.centralwidget)
        self.messageText.setGeometry(QtCore.QRect(20, 206, 592, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.messageText.setFont(font)
        self.messageText.setAlignment(QtCore.Qt.AlignCenter)
        self.messageText.setObjectName("messageText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XJConverter"))
        self.filesButton.setText(_translate("MainWindow", "Parse files"))
        self.label.setText(_translate("MainWindow", "XJConverter"))
        self.label_2.setText(_translate("MainWindow", "Converter:"))
        self.checkValue.setText(_translate("MainWindow", "Always use VALUE property"))
        self.checkLogs.setText(_translate("MainWindow", "Enable logs"))
        self.label_4.setText(_translate("MainWindow", "Files"))
        self.checkRemove.setText(_translate("MainWindow", "Remove original XML files"))
        self.checkXML.setText(_translate("MainWindow", "Parse .xml"))
        self.checkZIP.setText(_translate("MainWindow", "Parse .zip"))
        self.clearLogs.setText(_translate("MainWindow", "Clear logs"))
        self.asArray.setText(_translate("MainWindow", "All tags as array"))
        self.saveOptions.setText(_translate("MainWindow", "Save options"))
        self.dirButton.setText(_translate("MainWindow", "Parse directory"))
        self.messageText.setText(_translate("MainWindow", "Some text message"))

